name: Local Db Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.27.4
          architecture: arm64
      - run: |
          flutter pub get
          TEST_NO_LOGS=1 flutter test --platform macos